---
ButlerSpyglass:
  # Possible log levels are silly, debug, verbose, info, warn, error
  logLevel: verbose

  # Extract configuration
  extractFrequency: 60000     # Time between extraction runs. Milliseconds
  extractItemInterval: 500    # Time between requests to the engine API. Milliseconds
  extractItemTimeout: 5000    # Timeout for calls to the engine API. Milliseconds
  concurrentTasks: 1          # Simultaneous calls to the engine API. Example: If set to 3, this means 3 calls will be done at the same time, every extractItemInterval milliseconds.

  lineage:
    enableLineageExtract: true
    lineageFolder: ./out/lineage
    maxLengthDiscriminator: 1000       # Max characters of discriminator field (=source or destination of data) to store in per-app lineage disk file
    maxLengthStatement: 1000           # Max characters of statemenf field (e.g. SQL statement) to store in per-app lineage disk file

  script:
    enableScriptExtract: true
    scriptFolder: ./out/script

  configEngine:
    engineVersion: 12.170.2        # Qlik Associative Engine version to use with Enigma.js. ver 12.170.2 works with Feb 2019 
    server: <Fully qualified domain name of Qlik Sense Enterprise server from which data should be retrieved>
    serverPort: 4747
    isSecure: true
    headers:
      X-Qlik-User: UserDirectory=Internal;UserId=sa_repository
    ca: /path/to/certificate/experted/from/sense/root.pem
    cert: /path/to/certificate/experted/from/sense/client.pem
    key: /path/to/certificate/experted/from/sense/client_key.pem
    rejectUnauthorized: false

